Repository openshift/online-console-extensions, pull requests merged in 2018-04, with the labels that each got.

#32 Fix the incorrect default route format
  ui/custom-templates/about.html
Labels: size/XS

#34 Update generated templates
  dedicated/ui/assets/extensions/templates.js
  free/ui/assets/extensions/templates.js
  paid/ui/assets/extensions/templates.js
Labels: approved, lgtm, size/S

#36 merge master into stg
  dedicated/ui/assets/extensions/templates.js
  free/ui/assets/extensions/templates.js
  paid/ui/assets/extensions/templates.js
Labels: approved, size/S

#35 Update README for Jenkins job
  README.md
Labels: approved, lgtm, size/XS
