Repository openshift/online-console-extensions, pull requests merged in 2018-03, with the labels that each got.

#23 Check status after deployment
  ansible/roles/oso_console_extensions/tasks/main.yml
Labels: size/S

#24 Use rhel httpd image for custom builder
  s2i-custom-builder/Dockerfile
Labels: lgtm, size/XS

#25 patching "about: Update to include router information"
  free/ui/assets/extensions/templates.js
  paid/ui/assets/extensions/templates.js
  ui/assets/extensions/online-extensions.js
  ui/custom-templates/about.html
Labels: size/L

#26 Add damemi, sallyom, and dak1n1 to approvers
  OWNERS
Labels: lgtm, size/XS

#27 Add information about custom builder image
  README.md
Labels: approved, lgtm, size/S

#28 Generate dedicated templates
  dedicated/ui/assets/extensions/templates.js
Labels: approved, lgtm, size/L

#29 Add test for dedicated templates
  hack/check-generated-templates.sh
Labels: approved, lgtm, size/XS

#30 Remove thrasher from OWNERS file
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#31 Add Online no-issues icon to console
  ui/assets/extensions/online-extensions.js
Labels: approved, lgtm, size/M
